version: '3'

services:

  ### fastapi ######################################################

  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"

#    depends_on:
#      - redis-master
#      - postgres
    volumes:
      - ./:/app

